global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape metrics directly from the monitoring application
  - job_name: "api-monitoring"
    static_configs:
      - targets: ["monitoring:8080"]
    scrape_interval: 15s
    metrics_path: "/metrics"
    scheme: "http"

  # Optional: Scrape metrics from Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
