apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-system
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/version: "1.0"
  annotations:
    description: "BrightEdge API Monitoring System"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring-system
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring-system
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
