apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: monitoring-app-pdb
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-app
      app.kubernetes.io/component: application
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: metrics
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/component: visualization
