apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-app
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-scraper
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: brightedge-monitoring
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scraper
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: brightedge-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-scraper
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-app-role
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: brightedge-monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-app-binding
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: brightedge-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-app-role
subjects:
  - kind: ServiceAccount
    name: monitoring-app
    namespace: monitoring-system
