apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: brightedge-monitoring
    app.kubernetes.io/component: storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
